[package]
name = "tdo-server"
version = "0.1.0"
authors = ["Felix Döring <development@felixdoering.com>", "Felix Wittwer <dev@felixwittwer.de>"]

[dependencies]
tdo-core = "0.1.1"
tdo-notify = { git = "https://github.com/tdolist/tdo-notify" }